== A Poem

[verse]
____
Mount up, my soul, on contemplation's wing.
And sound high praises, to thy Heavenly King:
Who has destroyed death; that he may be forevermore a Savior unto thee and this line is really long.
Therefore to live is Christ, to die is gain,
That You with Him, forever may remain.

Maker supreme, of heav'n and earth,
Of sea, of air, and sky;
O! You who gav'st to all things birth,
Lord, hear me when I cry.

To Thee, invisible, I'll pray,
You only righteous God;
And Thee, omnipotent, obey,
And fear thy dreadful rod.

Riches or life, I do not crave,
Nor any transient things;
The one has wings, and in the grave
Are laid the proudest kings.

'Tis heav'nly wisdom I admire;
'Tis this is my request:
Oh, grant, great God, this my desire.
And I am fully blest:

Wisdom to worship thee aright,
To understand thy will.
To do my duty in thy sight,
And thy commands fulfil:

That when my fleeting sands are run,
And death shall set me free;
When the short thread of life is spun,
My soul may fly to thee:

Where I shall live eternally,
And fear no end of time;
But praise thy name, enthron'd on high,
You pow'rful God divine.

Not with a weak and mortal voice,
But in celestial strains;
In heav'n, the centre of my joys,
And end of all my pains
____
